a2lix_translation_form:
    locale_provider: default       # [1]
    locales: [en, ru, ua]      # [1-a]
    default_locale: ru             # [1-b]
    required_locales: [en, ru, ua]         # [1-c]
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"      # [2]