liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        my_thumb:
            quality: 90
            filters:
                thumbnail: { size: [300, 200], mode: outbound }
